package com.yc.blog.bean;

public class Flink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.id
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.name
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.url
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.img
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.description
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.status
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flink.sort
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.id
     *
     * @return the value of flink.id
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.id
     *
     * @param id the value for flink.id
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.name
     *
     * @return the value of flink.name
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.name
     *
     * @param name the value for flink.name
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.url
     *
     * @return the value of flink.url
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.url
     *
     * @param url the value for flink.url
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.img
     *
     * @return the value of flink.img
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.img
     *
     * @param img the value for flink.img
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.description
     *
     * @return the value of flink.description
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.description
     *
     * @param description the value for flink.description
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.status
     *
     * @return the value of flink.status
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.status
     *
     * @param status the value for flink.status
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flink.sort
     *
     * @return the value of flink.sort
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flink.sort
     *
     * @param sort the value for flink.sort
     *
     * @mbg.generated Wed Aug 14 20:09:58 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}